// Generated by Structorizer 3.30-01 

import java.util.Scanner;

/**
 */
public class LeerNumArray
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		// TODO: You may have to modify input instructions, 
		//       e.g. by replacing nextLine() with a more suitable call 
		//       according to the variable type, say nextInt(). 
		
		double[] datos = new double[]{0d, 0d, 0d, 0d, 0d, 0d, 0d, 0d, 0d, 0d};
		double limite;
		double sumaValores = 0d;
		int numTotalesPromedio = 0;
		double promedio;
		final int TOTAL_NUMEROS = 9;
		System.out.println("> Introduzca el listado de valores a continuación:");
		for (int i = 0; i <= TOTAL_NUMEROS; i += (1))
		{
			System.out.println("- Dato " + (i + 1) + ": ");
			datos[i] = (new Scanner(System.in)).nextLine();
		}
		System.out.println("> Introduzca el límite para calcular el promedio: ");
		limite = (new Scanner(System.in)).nextLine();
		for (int i = 0; i <= TOTAL_NUMEROS; i += (1))
		{
			if (datos[i] > limite)
			{
				sumaValores = sumaValores + datos[i];
				numTotalesPromedio = numTotalesPromedio + 1;
			}
		}
		if (numTotalesPromedio > 0)
		{
			promedio = sumaValores / numTotalesPromedio;
			System.out.println("> El promedio es: " + promedio);
		}
		else
		{
			System.out.println("> Ningún valor supera el límite propuesto");
		}
	}

}
