// Generated by Structorizer 3.30 

import java.util.Scanner;

/**
 */
public class CancionesMaximaMinimaTitulo
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		// TODO: You may have to modify input instructions, 
		//       e.g. by replacing nextLine() with a more suitable call 
		//       according to the variable type, say nextInt(). 
		
		final int T_INF_BAJO = -1;
		final int SEGUNDOS_MINUTO = 60;
		int minutosMaximo = T_INF_BAJO;
		int segundosMaximo = T_INF_BAJO;
		int mejorConversionMaxima = T_INF_BAJO;
		int minutosMinimo = SEGUNDOS_MINUTO;
		int segundosMinimo = SEGUNDOS_MINUTO;
		int mejorConversionMinima = 99999999999;
		int actualMinutos;
		int actualSegundos;
		int actualCancionConvertida = 0;
		String tituloMinima = "";
		String tituloMaxima = "";
		String tituloActual = "";
		final String CONDICION_PARADA = "";
		System.out.println("> Bienvenido. Introduzca las canciones según se le vaya pidiendo o pulse Enter para acabar.");
		System.out.println("# Introduzca el título de la canción: ");
		tituloActual = (new Scanner(System.in)).nextLine();
		System.out.println("- Introduzca la canción (minutos): ");
		actualMinutos = (new Scanner(System.in)).nextLine();
		System.out.println("+ Introduzca la canción (segundos): ");
		actualSegundos = (new Scanner(System.in)).nextLine();
		while (tituloActual != CONDICION_PARADA)
		{
			System.out.println("- Introduzca la canción (minutos): ");
			actualMinutos = (new Scanner(System.in)).nextLine();
			System.out.println("+ Introduzca la canción (segundos): ");
			actualSegundos = (new Scanner(System.in)).nextLine();
			actualCancionConvertida = (actualMinutos * SEGUNDOS_MINUTO) + actualSegundos;
			if (actualCancionConvertida > mejorConversionMaxima)
			{
				mejorConversionMaxima = actualCancionConvertida;
				minutosMaximo = actualMinutos;
				segundosMaximo = actualSegundos;
				tituloMaxima = tituloActual;
			}
			if (actualCancionConvertida < mejorConversionMinima)
			{
				mejorConversionMinima = actualCancionConvertida;
				minutosMinimo = actualMinutos;
				segundosMinimo = actualSegundos;
				tituloMinima = tituloActual;
			}
			System.out.println("# Introduzca el título de la canción: ");
			tituloActual = (new Scanner(System.in)).nextLine();
		}
		if (minutosMaximo == T_INF_BAJO && minutosMinimo == SEGUNDOS_MINUTO)
		{
			System.out.println("\n> No se introdujo ninguna canción");
		}
		else
		{
			System.out.println(("> Canción más larga: \"%s\" [%02d:%02d]\n") + (tituloMaxima) + (minutosMaximo) + (segundosMaximo));
			System.out.println(("> Canción más corta: %s [%02d:%02d]\n") + (tituloMinima) + (minutosMinimo) + (segundosMinimo));
		}
	}

}
