var listado = [{"persona":"Ada King",
  				"fichero":"adaKing"},
 				{"persona":"Ada Lovelace",
  				"fichero":"adaLovelace"},
  				{"persona":"Ángela Ruiz Robles",
  				"fichero":"AngelaRuizRobles"},
  				{"persona":"Carol Shaw",
  				"fichero":"CarolShaw"},
  				{"persona":"Frances Elizabeth Allen",
  				"fichero":"elizaallen"},
  				{"persona":"Evelyn Berezin",
  				"fichero":"Evelyn"},
  				{"persona":"Frances Elizabeth Snyder",
  				"fichero":"frances"},
  				{"persona":"Frances Bilas Spence",
  				"fichero":"francesBilas"},
  				{"persona":"Grace Murray Hopper",
  				"fichero":"graceMurray"},
  				{"persona":"Hedy Lamarr",
  				"fichero":"hedwigEva"},
  				{"persona":"Hedy Lamarr",
  				"fichero":"hedwigEvaMaria"},
  				{"persona":"Joan Elisabeth Lowther Murray",
  				"fichero":"joanElisabethLowther"},
  				{"persona":"Joyce K. Reynolds",
  				"fichero":"Joyce K. Reynolds_1"},
  				{"persona":"Jude Milhon",
  				"fichero":"judeMilhon"},
  				{"persona":"Kathleen 'Kay' McNulty Mauchly Antonelli",
  				"fichero":"Kathleen"},
  				{"persona":"Katie Bouman",
  				"fichero":"katieBouman"},
  				{"persona":"Lynn Ann Conway",
  				"fichero":"LynnAnnConway"},
  				{"persona":"Marlyn Wescoff Meltzer",
  				"fichero":"marlynWescoffMeltzer"},
  				{"persona":"Mary Allen Wilkes",
  				"fichero":"maryallen"},
  				{"persona":"Radia Joy Perlman",
  				"fichero":"radiaJoy"},
  				{"persona":"Ruth Lichterman Teitelbaum",
  				"fichero":"ruthLichterman"},
  				{"persona":"Shafrira Goldwasser",
  				"fichero":"Shafriragoldwasser"},
  				{"persona":"Susan Lois Graham",
  				"fichero":"susangraham"}];