var listado = [{"persona":"Ada King",
  				"fichero":"adaKing",
          "foto":"adaKing.jpg"},
 				{"persona":"Ada Lovelace",
  				"fichero":"adaLovelace",
          "foto":"AdaLovelace.jpg"},
  				{"persona":"Ángela Ruiz Robles",
  				"fichero":"AngelaRuizRobles",
          "foto":"angela.jpg"},
  				{"persona":"Carol Shaw",
  				"fichero":"CarolShaw",
          "foto":"carol.png"},
  				{"persona":"Frances Elizabeth Allen",
  				"fichero":"elizaallen",
          "foto":"francesElizabethAllen.jpg"},
  				{"persona":"Evelyn Berezin",
  				"fichero":"Evelyn",
          "foto":"evelynn.jpg"},
  				{"persona":"Frances Elizabeth Snyder",
  				"fichero":"frances",
          "foto":"frances.jpg"},
  				{"persona":"Frances Bilas Spence",
  				"fichero":"francesBilas",
          "foto":"Frances_Spence.jpg"},
  				{"persona":"Grace Murray Hopper",
  				"fichero":"graceMurray",
          "foto":"hopper.jpg"},
  				{"persona":"Hedy Lamarr",
  				"fichero":"hedwigEva",
          "foto":"hedwigeva.png"},
  				{"persona":"Hedy Lamarr",
  				"fichero":"hedwigEvaMaria",
          "foto":"hedwigeva.png"},
  				{"persona":"Joan Elisabeth Lowther Murray",
  				"fichero":"joanElisabethLowther",
          "foto":"joanelisabeth.jpg"},
  				{"persona":"Joyce K. Reynolds",
  				"fichero":"Joyce K. Reynolds_1",
          "foto":"Blog-ProfileA.jpg"},
  				{"persona":"Jude Milhon",
  				"fichero":"judeMilhon",
          "foto":"judeMilhon.jpg"},
  				{"persona":"Kathleen 'Kay' McNulty Mauchly Antonelli",
  				"fichero":"Kathleen",
          "foto":"Kay.jpg"},
  				{"persona":"Katie Bouman",
  				"fichero":"katieBouman",
          "foto":"katie.jpg"},
  				{"persona":"Lynn Ann Conway",
  				"fichero":"LynnAnnConway",
          "foto":"LynnAnn.jpg"},
  				{"persona":"Marlyn Wescoff Meltzer",
  				"fichero":"marlynWescoffMeltzer",
          "foto":"Wescoff_Meltzer_Marlyn.jpg"},
  				{"persona":"Mary Allen Wilkes",
  				"fichero":"maryallen",
          "foto":"MaryAllen.jpg"},
  				{"persona":"Radia Joy Perlman",
  				"fichero":"radiaJoy",
          "foto":"radiajoy.jpg"},
  				{"persona":"Ruth Lichterman Teitelbaum",
  				"fichero":"ruthLichterman",
          "foto":"ruthLichterman.jpg"},
  				{"persona":"Shafrira Goldwasser",
  				"fichero":"Shafriragoldwasser",
          "foto":"Shafriragoldwasser.jpg"},
  				{"persona":"Susan Lois Graham",
  				"fichero":"susangraham",
          "foto":"susanL.jpg"}];