// Generated by Structorizer 3.30-01 

import java.util.Scanner;

/**
 */
public class MostrarVectorCiclo
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		// TODO: You may have to modify input instructions, 
		//       e.g. by replacing nextLine() with a more suitable call 
		//       according to the variable type, say nextInt(). 
		
		final int MAX_NUMEROS = 10;
		final double COD_PARADA = 999;
		double[] datos = new double[]{0d, 0d, 0d, 0d, 0d, 0d, 0d, 0d, 0d, 0d};
		double actual = 0d;
		int cantidadValores = 0;
		int pos;
		int i = 0;
		System.out.println("> Introduzca hasta " + MAX_NUMEROS + " o " + COD_PARADA + " para terminar");
		System.out.println("+ Dato " + (cantidadValores + 1) + ": ");
		actual = (new Scanner(System.in)).nextLine();
		while ((cantidadValores < (MAX_NUMEROS-1)) && (actual != COD_PARADA))
		{
			datos[cantidadValores] = actual;
			cantidadValores = cantidadValores + 1;
			System.out.println("+ Dato " + (cantidadValores + 1) + ": ");
			actual = (new Scanner(System.in)).nextLine();
		}
		if (actual != COD_PARADA)
		{
			datos[cantidadValores] = actual;
			cantidadValores = cantidadValores + 1;
		}
		if (cantidadValores > 0)
		{
			System.out.println("> Introduzca la posición de inicio: ");
			pos = (new Scanner(System.in)).nextLine();
			System.out.println("> La lista de valores en ciclo desde la posición " + pos + " es:");
			System.out.println(datos[pos]);
			i = pos + 1;
			while ((i% cantidadValores) != pos)
			{
				System.out.println(datos[i % cantidadValores] + " ");
				i = i + 1;
			}
		}
		else
		{
			System.out.println("> No se introdujo ningún valor");
		}
	}

}
