package program.bifurcaciones;

// // Generated by Structorizer 3.29-13 

import java.util.Scanner;

/**
 */
public class Ecuacion2Grado {

	/**
	 * @param args
	 */
	public static void main(String[] args) {

		// Declaración inicial de las variables a usar
		double discriminante = 0d;
		double a = 0d;
		double b = 0d;
		double c = 0d;
		Scanner teclado = new Scanner(System.in);
		// Pedimos los datos por teclado
		System.out.print("A = ");
		a = teclado.nextDouble();
		System.out.print("B = ");
		b = teclado.nextDouble();
		System.out.print("C = ");
		c = teclado.nextDouble();
		teclado.close();
		// Comprobamos qué tipo de ecuación es
		if (a != 0d) {
			// Calculamos el discriminante
			discriminante = b * b - 4 * a * c;
			if (discriminante > 0d) {
				System.out.println(((-b + Math.sqrt(discriminante)) / (2 * a)));
				System.out.println(((-b - Math.sqrt(discriminante)) / (2 * a)));
			} else {
				if (discriminante == 0d) {
					System.out.println((-b / (2 * a)));
				} else {
					System.out.println("Resultado de tipo complejo");
				}
			}
		} else {
			if (b != 0d) {
				System.out.println((-c / b));
			} else {
				if (c != 0d) {
					System.out.println("No hay solución");
				} else {
					System.out.println("Infinitas soluciones");
				}
			}
		}
	}

}