// Generated by Structorizer 3.30-01 

import java.util.Scanner;

/**
 */
public class MediaListadoNombres
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		// TODO: You may have to modify input instructions, 
		//       e.g. by replacing nextLine() with a more suitable call 
		//       according to the variable type, say nextInt(). 
		
		final String CONDICION_PARADA = "fin";
		String actual;
		int cantidadNombres = 0;
		double media = 0d;
		int i = 0;
		System.out.println("> Introduzca los nombres de la lista o 'fin' (sin comillas) para terminar");
		System.out.println("+ Nombre " + (cantidadNombres + 1) + ": ");
		actual = (new Scanner(System.in)).nextLine();
		while (actual != CONDICION_PARADA)
		{
			media = media + length(actual);
			cantidadNombres++;
			System.out.println("+ Nombre " + (cantidadNombres + 1) + ": ");
			actual = (new Scanner(System.in)).nextLine();
		}
		if (cantidadNombres > 0)
		{
			media = media / cantidadNombres;
			System.out.println("> La media de los tamaños de los nombres dados es: " + media);
		}
		else
		{
			System.out.println("> No se introdujo ningún nombre");
		}
	}

}
