package github.crmprograming.primerodam.trimestreprimero.program.bucles;

// Generated by Structorizer 3.29-13 

import java.util.Scanner;

/**
 */
public class CompararEdades {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		Scanner teclado = new Scanner(System.in);
		int tuEdad;
		String nombre = "Ana Rosa";
		String mensaje;
		final int EDAD = 24;
		System.out.println(nombre + " tiene " + EDAD + " años de edad.");
		System.out.println("Introduce las edades (0 indica terminar)");
		System.out.println("Qué edad tienes tú: ");
		tuEdad = teclado.nextInt();
		while (tuEdad != 0) {
			if (tuEdad > 0) {
				if (tuEdad > EDAD) {
					mensaje = (tuEdad - EDAD) + " menor que tu";
				} else {
					if (EDAD > tuEdad) {
						mensaje = (EDAD - tuEdad) + " mayor que tu";
					} else {
						mensaje = "IGUAL EDAD";
					}
				}
			} else {
				mensaje = "Esto no puede ser una edad";
			}
			System.out.println(mensaje);
			System.out.println("Qué edad tienes tú: ");
			tuEdad = teclado.nextInt();
		}
		teclado.close();
		System.out.println("Adios, hasta la próxima ejecución...");
	}

}