package github.crmprograming.primerodam.trimestreprimero.program.bucles;

// Generated by Structorizer 3.29-13 

import java.util.Scanner;

public class Media {

	public static void main(String[] args) {

		double sumaNumeros = 0d;
		double numero;
		double media;
		int cuantos = 0;
		final double CONDICION_PARADA = 999d;
		Scanner teclado = new Scanner(System.in);

		System.out.println("Introduzca una lista de números (para acabar...)");
		numero = teclado.nextDouble();
		while (numero != CONDICION_PARADA) {
			sumaNumeros = sumaNumeros + numero;
			cuantos++;
			System.out.println("Introduzca una lista de números (para acabar...)");
			numero = teclado.nextDouble();
		}
		teclado.close();
		if (cuantos != 0) {
			media = sumaNumeros / (double) cuantos;
			System.out.println("La media es " + media);
		} else {
			System.out.println("No se dieron valores para calcular la media");
		}
	}

}
