// Generated by Structorizer 3.30-01 

import java.util.Scanner;

/**
 */
public class CaracteresFrase2
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		// TODO: You may have to modify input instructions, 
		//       e.g. by replacing nextLine() with a more suitable call 
		//       according to the variable type, say nextInt(). 
		
		String fraseIntroducida;
		char[] ArrayCadena;
		char caracter;
		int contador;
		int i;
		int j;
		System.out.println("Introduzca una frase");
		System.out.println("El programa enumerará los caracteres de la frase");
		fraseIntroducida = (new Scanner(System.in)).nextLine();
		if (longitud fraseIntroducida != 0)
		{
			ArrayCadena = fraseIntroducida;
			contador==1;
			for (int j = 1; j <= Longitud ArrayCadena-1; j += (1))
			{
				if (ArrayCadena[j] == ArrayCadena[0])
				{
					contador==contador+1;
				}
			}
			System.out.println(ArrayCadena[i]+ " " +contador);
			for (int i = 1; i <= Longitud ArrayCadena-1; i += (1))
			{
				// ArrayCadena[i] es un char aun no contabilizado 
				if (ArrayCadena[i] != ArrayCadena[0])
				{
					caracter = ArrayCadena[i];
					contador = 1;
					for (int j = i+1; j <= Longitud ArrayCadena-1; j += (1))
					{
						if (ArrayCadena[j] == caracter)
						{
							contador==contador+1;
							ArrayCadena[j] = ArrayCadena[0];
						}
					}
					System.out.println(ArrayCadena[i]+ " " +contador);
				}
			}
		}
	}

}
