// Generated by Structorizer 3.30-01 

import java.util.Scanner;

/**
 */
public class BuscadorIsla
{



	/**
	 * @param args
	 */
	public static void main(String[] args)
	{
		// TODO: Check and accomplish variable declarations: 
		
		// TODO: You may have to modify input instructions, 
		//       e.g. by replacing nextLine() with a more suitable call 
		//       according to the variable type, say nextInt(). 
		
		final int[] COD_ISLAS = {38, 35, 26, 14, 89, 33, 50};
		final String[] NOM_ISLAS = {"Tenerife", "Gran Canaria", "La Palma", "El Hierro", "La Gomera", "Fuerteventura", "Lanzarote"};
		int codBusqueda;
		int i;
		System.out.println("> Introduzca el código de la isla a buscar: ");
		codBusqueda = (new Scanner(System.in)).nextLine();
		i = 0;
		while (i < length(COD_ISLAS - 1) && codBusqueda != COD_ISLAS[i])
		{
			i = i + 1;
		}
		if (codBusqueda == COD_ISLAS[i])
		{
			System.out.println("> La isla con el código " + codBusqueda + " es " + NOM_ISLAS[i]);
		}
		else
		{
			System.out.println("> No existe isla con el código " + codBusqueda);
		}
	}

}
